# Site settings
title: UCHICAGO DSI CLUSTER INFORMATION
description: Information and policies for the UChicago Data Science Institute cluster
url: "https://dsi-clinic.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache

# Theme settings
theme: minimal-mistakes-jekyll

# Minimal Mistakes settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site structure
include:
  - pages
  - documents

# Collections
collections:
  resources:
    output: true
    permalink: /:collection/:path/
  policies:
    output: true
    permalink: /:collection/:path/
  tools:
    output: true
    permalink: /:collection/:path/
  howto:
    output: true
    permalink: /:collection/:path/


# Default layouts
defaults:
  # pages
  - scope:
      path: "pages"
      type: pages
    values:
      layout: single
      author_profile: false
      header:
        overlay_color: "#800000"
        overlay_filter: "0.5"
  # _resources
  - scope:
      path: ""
      type: resources
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "resources"
  # _policies
  - scope:
      path: ""
      type: policies
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "policies"
  # _tools
  - scope:
      path: ""
      type: tools
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "tools"
  # _howto
  - scope:
      path: ""
      type: howto
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "howto"

# Navigation
# Enable breadcrumbs
breadcrumbs: true

# Main links displayed in the masthead
header:
  image: /assets/images/dsi-header.png
  og_image: /assets/images/dsi-logo.webp
  
footer:
  links: [] 


sass:
  sass_dir: assets/css